# Generated by Django 4.1.7 on 2023-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_duration_alter_movie_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_by',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
