# Generated by Django 4.1.7 on 2023-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movieorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
